[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Deno_jll = "04572ae6-984a-583e-9378-9577a1c2574d"
Franklin = "713c75ef-9fc9-4b05-94a9-213340da978e"
FromFile = "ff7dd447-1dcb-4ce3-b8ac-22a812192de7"
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
NodeJS = "2bd173c7-0d6d-553b-b6af-13a54713934c"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoHooks = "0ff47ea0-7a50-410d-8455-4348d5de0774"
PlutoSliderServer = "2fc8631c-6f24-4c5b-bca7-cbb509c42db4"
PlutoTest = "cb4044da-4d16-4ffa-a6a3-8cad7f73ebdc"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
