[Export]
baked_state = false
baked_notebookfile = false
offer_binder = true
slider_server_url="https://computationalthinking-sliderserver-droplet.plutojl.org"
ignore_cache = [
    "index.jl",
]
create_index = false
exclude = [
    # these are in the repo but not used on the website
    "notebooks/week2/linear_transformation.jl",
    "notebooks/week2/OLD_linear_transformation.jl",
    "notebooks/week6/simulating_component_failure_live.jl",
    "notebooks/week8/discrete_and_continuous_old.jl",
    "notebooks/week8/pascal.jl",
    "notebook/week13/snowballearth_original.jl",
    "tools/generate_homepage_links.jl",
]

[SliderServer]
exclude=[
    # these are in the repo but not used on the website
    "notebooks/week2/linear_transformation.jl",
    "notebooks/week2/OLD_linear_transformation.jl",
    "notebooks/week6/simulating_component_failure_live.jl",
    "notebooks/week8/discrete_and_continuous_old.jl",
    "notebooks/week8/pascal.jl",
    "notebook/week13/snowballearth_original.jl",
    "tools/generate_homepage_links.jl",
    
    # not interactive
    "notebooks/basic_syntax.jl",
    "notebooks/week4/structure.jl",
    "notebooks/week12/how_to_collaborate_on_software.jl",
    
    # don't run homeworks
    "notebooks/week0/hw0.jl",
    "notebooks/week1/hw1.jl",
    "notebooks/week2/hw2.jl",
    "notebooks/week3/hw3.jl",
    "notebooks/week4/hw4.jl",
    "notebooks/week5/hw5.jl",
    "notebooks/week6/hw6.jl",
    "notebooks/week7/hw7.jl",
    "notebooks/week8/hw8.jl",
    "notebooks/week9/hw9.jl",
    "notebooks/week10/hw10.jl",
    "notebooks/week11/hw11.jl",
    "notebooks/week12/hw12.jl",
    "notebooks/week13/hw13.jl",
    "notebooks/week14/hw14.jl",
    "notebooks/week15/hw15.jl",
    "notebooks/week16/hw16.jl",
    "notebooks/week17/hw17.jl",
    "notebooks/week18/hw18.jl",
    "notebooks/week19/hw19.jl",
    "notebooks/week20/hw20.jl",
    "notebooks/week21/hw21.jl",
    "notebooks/week22/hw22.jl",
    "notebooks/week8/hw7.jl",
    "notebooks/week9/hw8.jl",
    "notebooks/week10/hw9.jl",
    "notebooks/week11/hw10.jl",
    "notebooks/week12/hw11.jl",
    "notebooks/week13/hw12.jl",
    "notebooks/week14/hw13.jl",
    "notebooks/week15/hw14.jl",
    "notebooks/week16/hw15.jl",
]
