[deps]
BetterFileWatching = "c9fd44ac-77b5-486c-9482-9798bd063cc6"
CommonMark = "a80b9123-70ca-4bc0-993e-6e3bcb318db6"
Deno_jll = "04572ae6-984a-583e-9378-9577a1c2574d"
Gumbo = "708ec375-b3d6-5a57-a7ce-8257bf98657a"
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MarkdownLiteral = "736d6165-7244-6769-4267-6b50796e6954"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoHooks = "0ff47ea0-7a50-410d-8455-4348d5de0774"
PlutoLinks = "0ff47ea0-7a50-410d-8455-4348d5de0420"
PlutoSliderServer = "2fc8631c-6f24-4c5b-bca7-cbb509c42db4"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
