name: Fall 22 - Export Pluto notebooks & Deploy
on:
    push:
        branches:
            - Fall22-PlutoPages-test
    workflow_dispatch:
concurrency:
    group: export
    cancel-in-progress: true

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Fall 22 source
              uses: actions/checkout@v2

            - name: ğŸ™Œ Install Julia
              uses: julia-actions/setup-julia@v1
              with:
                  version: 1.7.2

            - name: â± Cache notebook states
              uses: actions/cache@v2
              with:
                path: _cache
                key: ${{ runner.os }}-pluto_state_cache-v3-fall22-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}-${{ github.run_id }}
                restore-keys: |
                    ${{ runner.os }}-pluto_state_cache-v3-fall22-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}

            - name: â± Cache .julia
              uses: actions/cache@v2
              with:
                path: ~/.julia
                key: ${{ runner.os }}-dotjulia-v1-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}-${{ github.run_id }}
                restore-keys: |
                    ${{ runner.os }}-dotjulia-v1-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}

            # - name: ğŸ“… Checkout Fall 20 output
            #   uses: actions/checkout@v2
            #   with:
            #       path: Fall20-franklin-output
            #       ref: Fall20-franklin-output

            - name: ğŸ“… Checkout Fall20 and Spring21 output
              uses: actions/checkout@v2
              with:
                  path: Spring21-franklin-output
                  ref: Spring21-franklin-output

            - name: ğŸª´ Generate site
              run: julia --project=pluto-deployment-environment -e '
                  import Pkg;
                  Pkg.instantiate();

                  include("./generate.jl")'

            
            - name: ğŸ“° Upload site generation report
              uses: actions/upload-artifact@v2
              if: always()
              with:
                path: generation_report.html

            - name: ğŸ”€ Combine semesters into single site
              run: |
                mkdir www
                mv _site www/Fall22
                mv Spring21-franklin-output/Fall20/ www/Fall20
                mv Spring21-franklin-output/Spring21/ www/Spring21
                mv extra_outputs/* www

            - name: ğŸš€ Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: Fall22-output
                  FOLDER: www
