name: Spring 21 - Export Pluto notebooks & Deploy
on:
    push:
        branches:
            - Spring21
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Checkout Fall 20 page
              uses: actions/checkout@v2
              with:
                  path: Fall20-franklin-output
                  ref: Fall20-franklin-output

            - name: Install Julia
              uses: julia-actions/setup-julia@v1
              with:
                  version: 1.5
            - name: Run Pluto notebooks
              run: julia --project=bind-server-environment -e '
                  import Pkg;
                  Pkg.instantiate();

                  import PlutoUtils;
                  PlutoUtils.Export.github_action(; export_dir=".", offer_binder=true, binder_url="https://mybinder.org/build/gh/mitmath/18S191/e2dec90", bind_server_url="https://computationalthinking-bindserver.plutojl.org");'
            - name: Franklin
              run: julia -e '
                  using Pkg;
                  Pkg.add(["NodeJS", "JSON", "Franklin"]);
                  using NodeJS;

                  cp("notebooks", "website/notebooks");
                  cd("website");

                  run(`$(npm_cmd()) install highlight.js`);
                  using Franklin;
                  optimize(;minify=false);
                  mkdir("__site2");
                  mv("__site", "__site2/Spring21");
                  mv("../Fall20-franklin-output/Fall20", "__site2/Fall20");
                  write("__site2/index.html", """
                  <!DOCTYPE html>
                  <html>
                  <head><meta charset="utf-8"><script>
                  window.location.href=\"Spring21\"</script></head>
                  <body></body></html>""");
                  write("__site2/CNAME", "computationalthinking.mit.edu");'
            - name: Build and Deploy
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: Spring21-franklin-output
                  FOLDER: website/__site2
